# Лабораторная работа 5. Структурированные типы данных

# Строки

Строки представляют собой последовательности символов. Длина строки ограничена лишь объемом оперативной памяти компьютера. 

Поддерживают обращение к элементу по индексу, получение среза, конкатенацию (оператор +), повторение (оператор *), а также проверку на вхождение (операторы in и not in).

Относятся к неизменяемым типам данных. Практически все операция в качестве значения возвращают новую строку. Поэтому для рациональной работы со строками желательно использовать специальные строковые методы.

Например, доступны следующие манипуляции:

In [1]:
s = "Hello, World!"
print(s, type(s), id(s))

Hello, World! <class 'str'> 1741085358384


In [2]:
s[-1] = "?"
print(s, type(s), id(s))

TypeError: 'str' object does not support item assignment

Для обозначения однострочечных символов (строк) можно использовать " " или ' ':

In [4]:
s = s[:-1] + "?" + '...'
print(s, type(s), id(s))

Hello, World?..?... <class 'str'> 1741085275280


Их комбинация задаёт ковычки в строке:

In [5]:
s = "Кто сказал " + '"Hello, World!"' + '?'
print(s, type(s), id(s))

Кто сказал "Hello, World!"? <class 'str'> 1741086040112


Для создания многострочечных строк используйте тройные ковычки:

In [12]:
s = """Строка 1
Строка 2
Строка 3
"""
print(s, type(s), id(s))

Строка 1
Строка 2
Строка 3
 <class 'str'> 2425413148208


Если строка не присваивается переменной, то она считается строкой документирования. Такая строка сохраняется в атрибуте_doc_того объекта, в котором расположена. 

Например:

In [34]:
def test():
    """Это описание функции"""
    pass

In [35]:
print (test.__doc__)

Это описание функции


Строковые методы.

Для строк есть множество методов. Посмотреть их можно по команде

In [13]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


Получить информацию по каждому можно следующим образом

In [14]:
help(str.split)

Help on method_descriptor:

split(self, /, sep=None, maxsplit=-1)
    Return a list of the words in the string, using sep as the delimiter string.
    
    sep
      The delimiter according which to split the string.
      None (the default value) means split according to any whitespace,
      and discard empty strings from the result.
    maxsplit
      Maximum number of splits to do.
      -1 (the default value) means no limit.



In [15]:
help(str.join)

Help on method_descriptor:

join(self, iterable, /)
    Concatenate any number of strings.
    
    The string whose method is called is inserted in between each given string.
    The result is returned as a new string.
    
    Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'



Рассмотрим наиболее интересные из них:
    
- метод split() позволяет разбить строку по указанному разделителю (по умолчанию - пробелам), в результате получается список слов;
- метод join() выполняет обратное действие, формирует из списка строку с определённым объединителем;
- метод format() выполняет запонение строки в зарезервированные {} места.

Например:

In [16]:
"Хорошо бы разделить эту строку на части".split()

['Хорошо', 'бы', 'разделить', 'эту', 'строку', 'на', 'части']

In [19]:
s = "Но не каждую строку, которую надо разделить, нужно делить по пробелам!!!"

In [20]:
s.split(', ')

['Но не каждую строку',
 'которую надо разделить',
 'нужно делить по пробелам!!!']

In [21]:
s.split('!')

['Но не каждую строку, которую надо разделить, нужно делить по пробелам',
 '',
 '',
 '']

In [25]:
s.split('!', 1)  #  ограничем максимальное чило делений

['Но не каждую строку, которую надо разделить, нужно делить по пробелам', '!!']

In [26]:
s2 = s.split(', ')
print(s2)

['Но не каждую строку', 'которую надо разделить', 'нужно делить по пробелам!!!']


In [31]:
s1 = ', '
print(s1, type(s1), id(s1))

,  <class 'str'> 2425412618352


In [33]:
s1 = s1.join(s2)
print(s1, type(s1), id(s1))

Но не каждую строку, которую надо разделить, нужно делить по пробелам!!! <class 'str'> 2425413268400


Строковый метод format() позволяет создать строку форматной вставкой в неё данных:

In [37]:
size = "length - {}, width - {}, height - {}"
size.format(3, 6, 2.3)

'length - 3, width - 6, height - 2.3'

In [39]:
size = "length - {2}, width - {0}, height - {1}"
size.format(3, 6, 2.3)

'length - 2.3, width - 3, height - 6'

In [41]:
size = "length - {length:5.3f}, width - {width:5.3f}, height - {height:5.3f}"
size.format(width=3.3333333, height=6.7896, length=2.3)

'length - 2.300, width - 3.333, height - 6.790'

# Списки

Список в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры). Эллементы списка доступны по индексу начинающегося с 0. Список является изменяемым типом данных - любой его эллемнт можно изменить.

Список задаётся перечислением его элементов в квадратных скобках через запятую или с помощью функции list(), например

In [42]:
List = [1, 2.0, '3', [4]]
List

[1, 2.0, '3', [4]]

In [43]:
List[2] = 'three'
List

[1, 2.0, 'three', [4]]

Списки поддерживают следующие базовые операции:

In [3]:
l=[0,1,2,3,4,5,6,7]
l

[0, 1, 2, 3, 4, 5, 6, 7]

- удаление эллемента

In [45]:
del l[3]
l

[0, 1, 2, 4, 5, 6, 7]

- добавить эллемента в заданную позицию

In [46]:
l.insert(3,0)
l

[0, 1, 2, 0, 4, 5, 6, 7]

- добавить эллемента в конец

In [47]:
l.append(8)
l

[0, 1, 2, 0, 4, 5, 6, 7, 8]

- добавить несколько эллементов в конец

In [5]:
l.extend([9,10,11])
l

[0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11]

In [7]:
del l[0]

In [9]:
l

[1, 2, 3, 4, 5, 6, 7, 9, 10, 11]

In [1]:
[6, 7] + [4]

[6, 7, 4]

# Генераторы списков

Можно также воспользоваться генераторами списков:

In [57]:
x = [i for i in range(10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Генераторы списков могут иметь сложную структуру — например, состоять из нескольких вложенных циклов for и (или) содержать оператор ветвления if после цикла. Для примера получим четные элементы списка и умножим их на 10:

In [58]:
x2 = [ i*10 for i in x if i%2 == 0 ]
print(x2)

[0, 20, 40, 60, 80]


Этот код эквивалентен коду:

In [59]:
x2 = []
for i in x:
    if i % 2 == 0: 
        x2.append(i*10) 
print(x2)

[0, 20, 40, 60, 80]


# Копирование списков

Операция копирования для листов, имеет особенности

In [50]:
y = x # это не копирование!!!
print(id(x), id(y))

2425413357064 2425413357064


Правильное копирование:

In [52]:
y1 = list(x)
y2 = x.copy()
y3 = x[:]

print(y1, id(y1))
print(y2, id(y2))
print(y3, id(y3))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413349128
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413247688
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413354888


Объединение листов:

In [54]:
x = x[:2] + x[-2:]
print(x, type(x), id(x))

[0, 1, 8, 9] <class 'list'> 2425413318088


# Кортеж

Кортеж в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры).

Его эллементы доступны по индексу начинающегося с 0. Кортеж является не изменяемым типом данных - его эллемнты нельзя менять.

Кортеж задаётся перечислением его элементов в круглых скобках через запятую или с помощью функции tuple(), например

In [86]:
Tuple = (1, 2.0, '3', [4, 5])
print(Tuple[0],Tuple[1],Tuple[2],Tuple[3])

1 2.0 3 [4, 5]


In [87]:
Tuple[2] = 'three'
print(Tuple[0],Tuple[1],Tuple[2],Tuple[3])

TypeError: 'tuple' object does not support item assignment

In [15]:
Tuple[3]

[4, 5]

In [16]:
Tuple[3][0]

4

In [17]:
Tuple[3][0]=-4
Tuple[3][0]

-4

# Множества

Множества в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры). В отличии от списков и картежей, множество не итерируется по индуксу.

In [10]:
Set = set([2.0, 1, 2, 1, '3', 4])
Set

{1, 2.0, '3', 4}

In [16]:
Set.add(1)
Set

{-1, 1, 2.0, '3', 4}

Почему пропала одна 1?

Вероятно, наиболее важной операцией с множеством является операция праверки принадлежности, и для неё нужно знать только уникальные эллементы множества. По этой же причине отсутствует возможность обращаться к эллементам по индексу.

In [11]:
x = 1

if x in Set:
    print('принадлежит множеству')
else:
    print('не принадлежит множеству')

принадлежит множеству


In [12]:
dir(set)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [13]:
help(set.add)

Help on method_descriptor:

add(...)
    Add an element to a set.
    
    This has no effect if the element is already present.



# Словари

Словарь в Python - структура содержит пары "ключ" - "значение" (их порядок несущественен). Это одина из наиболее полезных и гибких структур имеющихся в Python. Словари реализованы как хэш-таблицы, так что поиск даже в больших словарях очень эффективен.

Например, с помощью словоря можно эмулировать работу оператора множественного выбора аналогичного switch:

In [14]:
def switch_dict(x):
    return {
        "a": 1,
        "b": 2,
        "c": 3
    }.get(x, -1)

In [15]:
switch_dict('a')

1

In [16]:
switch_dict('6')

-1

# Массивы (numpy)

Менее стандартной, но очень полезной является структура массив, объединяющая эллементы одинакового типа.

In [18]:
import numpy as np

In [6]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

Очень часто возникает задача создания массива определенного размера, причем чем заполнен массив абсолютно неважно. В этом случае можно воспользоваться циклами или генераторами списков (кортежей), но NumPy для таких случаев предлагает более быстрые и менее затратные функции-заполнители.

Полезными оказываются следующие функции (по умолчанию, тип создаваемого массива - float64.):

- zeros() - заполняет массив нулями, 

In [114]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros(3)

array([0., 0., 0.])

- eye() - создаёт единичную матрицу, 

In [115]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- empty - заполняет матрицу случайными числами, которые зависят от состояния памяти. 

In [116]:
np.empty([3, 3])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Для создания последовательностей чисел NumPy предоставляет функции arange() и linspace(), которая возвращает одномерные массивы:

- np.arange(From, To, Step) - построить массив чисел от From (включая) до To (не включая) с шагом Step:

In [117]:
np.arange(10)   #  От 0 до указанного числа с шагом 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.arange(10, 20)    #  От 10 до 20 с шагом 1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [124]:
np.arange(10, 100, 10)    #  Диапазон с заданным шагом

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [125]:
np.arange(0, 1, 0.1)    #  Аргументы могут иметь тип float

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

- np.linspace(From, To, Num) - построить массив чисел от From (включая) до To (включая) с колличеством эллементов Num:

In [123]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Упражнение 1.

С клавиатуры (неограниченное количество раз) вводится некоторая последовательность значений, необходимо сохранить только уникальные символы (цифры и буквы). И после окончания ввода вывести сохранённые символы.

In [ ]:
def unique_characters(sequence):
    unique_chars = set()
    for char in sequence:
        if char.isalnum():
            unique_chars.add(char)
    return unique_chars

def main():
    sequence = input("Enter a sequence of characters: ")
    unique_chars = unique_characters(sequence)
    print("Unique characters:", unique_chars)

if __name__ == "__main__":
    main()

# Упражнение 2. Эффективный размер массива (стек).

Стек, дека, очередь. Массив с дополнительными параметрами (размер выделенной памяти и объём занятой памяти). Позволяют за константное время добавлять и убирать элементы в начало и конец эффективного размера массива.

Напишите функцию которая реализует работу стека: 
1. внутри определён массив numpy заданного размера и целочисленный параметр фиксирующий степень заполненности массива;
2. функция принимает значение x и индиксатор действия (0 - чтение из стека, 1 - запись в стек); в случае чтения возвращает значение из конца массива или False, если стек пуст; при записи возвращает логическую переменную индикатор успешности операции;
3. при операциях чтения и записи должна проверяться корректность этого действия связанная с размерами стека.

In [ ]:
import numpy as np

class Stack:
    def __init__(self, size, occupancy):
        self.array = np.zeros(size, dtype=int)
        self.size = size
        self.occupancy = occupancy
        self.top = -1

    def is_empty(self):
        return self.top == -1

    def is_full(self):
        return self.top == int(self.size * self.occupancy) - 1

    def push(self, x):
        if self.is_full():
            return False
        self.top += 1
        self.array[self.top] = x
        return True

    def pop(self):
        if self.is_empty():
            return False
        top_value = self.array[self.top]
        self.top -= 1
        return top_value

    def stack_operation(self, action, x=None):
        if action == 0:
            return self.pop() if not self.is_empty() else False
        elif action == 1:
            return self.push(x)
        else:
            return False

# Example
size = 10
occupancy = 0.8
stack = Stack(size, occupancy)

print("Push 1:", stack.stack_operation(1, 1))
print("Push 2:", stack.stack_operation(1, 2))
print("Pop:", stack.stack_operation(0))
print("Pop:", stack.stack_operation(0))

# Упражнение 3. Эффективный размер массива (множество).

Как мы уже поняли, множество в Python это совокупность уникальных объектов не доступных по индексу. Адаптируйте предыдущую программу к работе в таком режиме.

Т.е.: 
1. дописываться могут только значения не записанные ранее;
2. функция принимает одно значение x (True - вывод всего множества, числовое значение - запись в множество); в случае если множество пусто возвращается False; при записи возвращает логическую переменную индикатор успешности операции;
3. при операциях чтения и записи должна проверяться корректность этого действия связанная с размерами множества.

P.S. Попробуйте реализовать пункт с выводом значений по возрастанию через работу с дополнительным массивом индексов (перестановок). Или начиная запись в множество с середины массива...

# Функции для итерируемых объектов.

Наиболее полезными для итерируем объектов являются функции:
- map() - позволяет применить заданную функцию к каждому элементу последовательности, возвращает объект, поддерживающий итерации,
- zip() - возвращает кортеж, содержащий элементы последовательностей расположенных на одинаковом смещении,
- filter() - позволяет выполнить проверку элементов последовательности.

In [62]:
def fun(elem):
    return elem + 10 

arr = [1, 2, 3, 4, 5]
print(list(map(fun, arr)))

[11, 12, 13, 14, 15]


In [63]:
list(zip([ 1, 2, 3], [4, 5, 6], [7, 8, 9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [67]:
arrl = [1, 2, 3, 4, 5]
arr2 = [10, 20, 30, 40, 50]
arrЗ = [100, 200, 300, 400, 500]

arr = [х + у + z for (х, у, z) in zip(arrl, arr2, arrЗ)]
print(arr)

[111, 222, 333, 444, 555]


или что тоже самое

In [68]:
def fun(a,b,c):
    return a+b+c 

print(list(map(fun, arrl, arr2, arrЗ)))

[111, 222, 333, 444, 555]


In [69]:
def fun(elem):
    return elem % 2 == 0

list(filter(fun, arr))

[222, 444]

# Генераторы словарей

In [72]:
keys = ["а", "Ь", "c"]
values = [1, 2, 3] 
dict_kv = {k: v for (k, v) in zip(keys, values)}
dict_kv

{'а': 1, 'Ь': 2, 'c': 3}

# Упражнение 4.

Создайте функцию принимающую двумерную таблицу, работающую со всеми возможными итерируемыми типами данных подходящими для её хранения (лист, словарь, картеж, массив и т.д.). Функция должна выполнять вывод строк этой таблици в случайном порядке. 

Насколько сложно было бы сделать аналогичный вывод для столбцов?

In [ ]:
import random

def print_table_rows(table):
    keys = list(table.keys()) if isinstance(table, dict) else range(len(table))


    random.shuffle(keys)


    for key in keys:
        print(table[key])

# Example
table_list = [
    ["Ellon", 25, "Engineer"],
    ["Bill", 30, "Doctor"],
    ["Jeff", 35, "Artist"]
]

table_dict = {
    1: ["Ellon", 25, "Engineer"],
    2: ["Bill", 30, "Doctor"],
    3: ["Jeff", 35, "Artist"]
}

print("Printing rows of table_list in random order:")
print_table_rows(table_list)

print("\nPrinting rows of table_dict in random order:")
print_table_rows(table_dict)


# Домашнее задание (базовое):

# Задание 1.

С клавиатуры вводится строка, включающая строчные и прописные буквы. Требуется вывести ту же строку в изменённом регистре, тип регистра зависит от того, каких букв больше. При равном количестве букв в заглавном и проптсном регистре - выводится оригинальная строка. 

Например, вводится строка "HeLLo World", она должна быть преобразована в "hello world", потому что в исходной строке малых букв больше. 

В программе можно использовать строковые методы: upper() (преобразование к верхнему регистру) и lower() (преобразование к нижнему регистру), isupper() и islower() (проверяющие регистр строки или символа).

In [ ]:
def transform_string(s):
    # Подсчитываем количество символов в верхнем и нижнем регистрах
    upper_count = sum(1 for char in s if char.isupper())
    lower_count = sum(1 for char in s if char.islower())
    
    # Принимаем решение о регистре для вывода
    if upper_count > lower_count:
        # Если больше символов в верхнем регистре, преобразуем всю строку к верхнему регистру
        return s.upper()
    elif lower_count > upper_count:
        # Если больше символов в нижнем регистре, преобразуем всю строку к нижнему регистру
        return s.lower()
    else:
        # Если количество символов в верхнем и нижнем регистрах одинаково, возвращаем оригинальную строку
        return s

# Ввод строки с клавиатуры
input_string = input("Введите строку: ")

# Вызываем функцию для преобразования строки и выводим результат
transformed_string = transform_string(input_string)
print("Преобразованная строка:", transformed_string)

# Задание 2

Дано слово "объектно-ориентированный". Используя индексацию и срезы составьте из него как можно больше слов "объект", "ориентир", "тир", "кот", "рента" и тд. Выведите их на экран.

In [ ]:
word = "объектно-ориентированный"

# Слово "объект"
word_obj = word[:word.index('-')]
print("Слово 'объект':", word_obj)

# Слово "ориентир"
start_orientir = word.index('-') + 1
end_orientir = word.rindex('и')
word_orientir = word[start_orientir:end_orientir]
print("Слово 'ориентир':", word_orientir)

# Слово "тир"
word_tir = word[word.rindex('и') + 1:]
print("Слово 'тир':", word_tir)

# Слово "кот"
letters_kot = ['к', 'о', 'т']
word_kot = ''.join([char for char in letters_kot if char in word])
print("Слово 'кот':", word_kot)

# Слово "рента"
start_renta = word.rindex('о') + 1
word_renta = word[start_renta:]
print("Слово 'рента':", word_renta)

# Задание 3

Строковый метод isdigit() проверяет, состоит ли строка только из цифр. Напишите программу, которая запрашивает с ввода целые числа и выводит их сумму. В случае некорректного ввода программа не должна завершаться с ошибкой, а должна продолжать работу, удаляя из введённой строки все символы кроме цифр. При отсутствии цифр запрс пользователю повторяется.

Обработчик исключений try-except использовать нельзя.

In [ ]:
def sum_of_digits():
    while True:
        user_input = input("Введите целые числа (для завершения введите 'done'): ")
        clean_input = ''.join(filter(str.isdigit, user_input))  # Фильтруем только цифры из ввода
        
        if clean_input:  # Если строка после фильтрации не пустая
            numbers = list(map(int, clean_input))  # Преобразуем каждую цифру в целое число
            total_sum = sum(numbers)  # Считаем сумму цифр
            print("Сумма введенных цифр:", total_sum)
            break
        else:
            print("Некорректный ввод. Пожалуйста, введите цифры.")

# Вызываем функцию для выполнения программы
sum_of_digits()

# Задание 4

Создайте словарь, где ключами являются числа, а значениями – строки. Примените к нему метод items(), полученный объект dict_items передайте в написанную вами функцию, которая создает и возвращает новый словарь, "обратный" исходному, т. е. ключами являются строки, а значениями – числа. 

In [ ]:
def reverse_dictionary(dict_items):
    reversed_dict = {}  # Создаем пустой словарь для обратных значений
    for number, string in dict_items:
        reversed_dict[string] = number  # Заполняем обратный словарь значениями из исходного
    return reversed_dict

# Создаем исходный словарь
original_dict = {
    1: "one",
    2: "two",
    3: "three",
    4: "four"
}

# Получаем представление словаря в виде dict_items
dict_items = original_dict.items()

# Вызываем функцию reverse_dictionary и передаем ей dict_items
reversed_dict = reverse_dictionary(dict_items)

# Выводим обратный словарь
print("Обратный словарь:")
print(reversed_dict)

# Задание 5. (Снова в школу...)

Опишите структуру данных (базу данных) на основе словаря и интерфейс работы с ней (функцию). 

Создайте словарь school, и наполните его данными, которые бы отражали количество учащихся в разных классах (1а, 1б, 2б, 6а, 7в и т.п.). И функцию для внесения изменений в словарь в рамках следующего функционала: 
а) в одном из классов изменилось количество учащихся; 
б) в школе появился новый класс; 
с) в школе был расформирован (удален) класс, в связи с чем ученики были равномерно распределены по другим; 
d) выгрузка данных: общее количество учащихся в школе, общее колличество классав, распределение учеников по классам.

P.S. Дополнительно.

Подумайте как лучше всего хранить такую базу данных в файле. Попробуйте реализовать свою идею.

In [ ]:
school = {
    "1а": 25,
    "1б": 28,
    "2б": 30,
    "6а": 22,
    "7в": 26
}
def change_class_size(class_name, new_size):
    if class_name in school:
        school[class_name] = new_size
        print(f"Количество учащихся в классе {class_name} изменено на {new_size}")
    else:
        print(f"Класс {class_name} не найден в базе данных")
def add_new_class(class_name, initial_size):
    if class_name not in school:
        school[class_name] = initial_size
        print(f"Добавлен новый класс {class_name} с количеством учащихся {initial_size}")
    else:
        print(f"Класс {class_name} уже существует в базе данных")
def dissolve_class(class_name):
    if class_name in school:
        total_students = school.pop(class_name)  # Удаляем класс из словаря и получаем количество учеников
        remaining_classes = len(school)
        if remaining_classes > 0:
            new_size = total_students // remaining_classes
            for cls in school:
                school[cls] += new_size
            print(f"Класс {class_name} расформирован, ученики равномерно распределены по остальным классам")
        else:
            print("Невозможно расформировать последний класс")
    else:
        print(f"Класс {class_name} не найден в базе данных")
def export_data():
    total_students = sum(school.values())
    total_classes = len(school)
    print(f"Общее количество учащихся в школе: {total_students}")
    print(f"Общее количество классов в школе: {total_classes}")
    print("Распределение учеников по классам:")
    for class_name, num_students in school.items():
        print(f"{class_name}: {num_students} учеников")       

# Домашнее задание (дополнительное):

# Задание. Реверс словаря.

Создайте словарь, где ключами являются цифры, а значениями – строки. Передайте словарь в функцию, которая создает и возвращает новый словарь, "обратный" исходному, при этом ключами являются буквы составляющие строки, а значениями – числа составленные из цифр в порядке соответствующем.

Например: 

Исходный словарь: {1: 'аcc', 2: 'сab', 3: 'ccb'}

Выходной словарь: {'а': 12, 'b': 23, 'c': 11233}

In [ ]:
def reverse_dictionary_letters_to_numbers(input_dict):
    reversed_dict = {}  # Создаем пустой словарь для обратных значений
    for key, value in input_dict.items():
        for char in value:
            if char.isalpha():  # Проверяем, является ли символ буквой
                if char in reversed_dict:
                    reversed_dict[char] = int(str(reversed_dict[char]) + str(key))  # Добавляем цифру к числу
                else:
                    reversed_dict[char] = key  # Создаем новую запись в обратном словаре
    return reversed_dict

# Создаем исходный словарь
original_dict = {
    1: 'аcc',
    2: 'сab',
    3: 'ccb'
}

# Вызываем функцию reverse_dictionary_letters_to_numbers и передаем ей исходный словарь
reversed_dict = reverse_dictionary_letters_to_numbers(original_dict)

# Выводим обратный словарь
print("Обратный словарь:")
print(reversed_dict)

# Задание. Разрезание таблиц. 

Заполните квадратную таблицу порядка n по спирали по часовой стрелке начиная с левого верхнего угла. В напишите функцию принимающую данную таблицу в подходящем формате, найдите строку с наибольшим количеством нулей и столбец с максимальной суммой элементов. Разрежьте по этой строке и столбцу таблицу и верните из функции получившийся результат как отдельные таблицы, после чего выведете их на печать.

In [ ]:
def generate_spiral_table(n):
    table = [[0] * n for _ in range(n)]
    num = 1
    top_row, bottom_row = 0, n - 1
    left_col, right_col = 0, n - 1

    while top_row <= bottom_row and left_col <= right_col:
        # Fill top row
        for col in range(left_col, right_col + 1):
            table[top_row][col] = num
            num += 1
        top_row += 1

        # Fill right column
        for row in range(top_row, bottom_row + 1):
            table[row][right_col] = num
            num += 1
        right_col -= 1

        # Fill bottom row
        for col in range(right_col, left_col - 1, -1):
            table[bottom_row][col] = num
            num += 1
        bottom_row -= 1

        # Fill left column
        for row in range(bottom_row, top_row - 1, -1):
            table[row][left_col] = num
            num += 1
        left_col += 1

    return table

def find_max_zero_row_and_max_sum_column(table):
    max_zero_count = 0
    max_zero_row = 0
    max_sum = float('-inf')
    max_sum_column = 0

    for i, row in enumerate(table):
        zero_count = row.count(0)
        if zero_count > max_zero_count:
            max_zero_count = zero_count
            max_zero_row = i

        row_sum = sum(row)
        if row_sum > max_sum:
            max_sum = row_sum
            max_sum_column = row.index(max(row))

    return max_zero_row, max_sum_column

def cut_table(table, max_zero_row, max_sum_column):
    cut_rows = [row[:max_sum_column] for row in table[:max_zero_row]]
    cut_rows.extend(row[:max_sum_column] + row[max_sum_column+1:] for row in table[max_zero_row+1:])
    return cut_rows

# Example
n = 5
spiral_table = generate_spiral_table(n)
print("Original table:")
for row in spiral_table:
    print(row)

max_zero_row, max_sum_column = find_max_zero_row_and_max_sum_column(spiral_table)
print("Row with the maximum number of zeros:", spiral_table[max_zero_row])
print("Column with the maximum sum of elements:", [row[max_sum_column] for row in spiral_table])

cut_rows = cut_table(spiral_table, max_zero_row, max_sum_column)
print("\nResult after cutting:")
for row in cut_rows:
    print(row)


# Задание. Пары.

На вход программы поступает последовательность из N целых положительных чисел, все числа в последовательности различны. Рассматриваются все пары различных элементов последовательности (элементы пары не обязаны стоять в последовательности рядом, порядок элементов в паре не важен). Необходимо определить количество пар, для которых произведение элементов делится на 26.
Описание входных и выходных данных.

В первой строке входных данных задаётся количество чисел N (1 ≤ N ≤ 1000). В каждой из последующих N строк записано одно целое положительное число, не превышающее 10 000.

В качестве результата программа должна напечатать одно число: количество пар, в которых произведение элементов кратно 26.

Пример входных данных: 4 2 6 13 39

Пример выходных данных: 4

Из четырёх заданных чисел можно составить 6 попарных произведений:

2·6 = 12 

2·13 = 26 

2·39 = 78 

6·13 = 78

6·39 = 234 

13·39 = 507

Из них на 26 делятся 4 произведения:

2·13=26

2·39=78

6·13=78

6·39=234

Требуется написать эффективную по времени и по памяти программу для решения описанной задачи.

(Программа считается эффективной по времени, если при увеличении количества исходных чисел N в k раз время работы программы увеличивается не более чем в k раз. Программа считается эффективной по памяти, если память, необходимая для хранения всех переменных программы, не превышает 1 Кбайт и не меняется с ростом N.)

In [ ]:
def count_pairs_divisible_by_26(numbers):
    count_div_2 = 0
    count_div_13 = 0
    product_counts = {i: 0 for i in range(26)}

    # Проходим по всем числам в последовательности
    for num in numbers:
        if num % 2 == 0:
            count_div_2 += 1
        if num % 13 == 0:
            count_div_13 += 1

        remainder = num % 26
        product_counts[remainder] += 1

    # Считаем количество пар с произведением, делющимся на 26
    result = 0

    # Перебираем все возможные остатки r1 и r2
    for r1 in range(26):
        for r2 in range(26):
            if (r1 * r2) % 26 == 0:
                count_r1 = product_counts[r1]
                count_r2 = product_counts[r2]
                result += count_r1 * count_r2

    return result